replicaCount: 3

image:
  repository: nginx
  tag: "1.27.0"
  pullPolicy: IfNotPresent

resources:
  requests:
    cpu: "200m"
    memory: "256Mi"
  limits:
    cpu: "500m"
    memory: "512Mi"

autoscaling:
  minReplicas: 3
  maxReplicas: 10
  targetCPUUtilizationPercentage: 60

livenessProbe:
  path: /
  initialDelaySeconds: 10
  periodSeconds: 15

readinessProbe:
  path: /
  initialDelaySeconds: 5
  periodSeconds: 10