replicaCount: 1

image:
  repository: nginx
  tag: "1.27.0"
  pullPolicy: IfNotPresent

resources:
  requests:
    cpu: "100m"
    memory: "128Mi"
  limits:
    cpu: "200m"
    memory: "256Mi"

autoscaling:
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 80

livenessProbe:
  path: /
  initialDelaySeconds: 10
  periodSeconds: 15

readinessProbe:
  path: /
  initialDelaySeconds: 5
  periodSeconds: 10